<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Game;
use App\Models\Publisher;
use App\Models\Category;

class GameSeeder extends Seeder
{
    public function run(): void
    {
        // Helper closure
        $pub  = fn($name) => Publisher::where('name', $name)->value('id');
        $cat  = fn($name) => Category::where('name', $name)->value('id');

        $games = [
            [
                'title'        => 'Elden Ring',
                'description'  => 'An action RPG in a vast open world created by FromSoftware and George R.R. Martin. Explore the shattered world of the Lands Between.',
                'price'        => 499000,
                'release_date' => '2022-02-25',
                'developer'    => 'FromSoftware',
                'publisher'    => 'FromSoftware',
                'category'     => 'RPG',
                'stock'        => 9999,
                'image'        => '/images/games/elden_ring.jpg',
                'rating'       => 9.5,
            ],
            [
                'title'        => 'Cyberpunk 2077',
                'description'  => 'An open-world RPG set in Night City, a megalopolis obsessed with power and body modification. You play as V, a mercenary outlaw.',
                'price'        => 379000,
                'release_date' => '2020-12-10',
                'developer'    => 'CD Projekt Red',
                'publisher'    => 'CD Projekt Red',
                'category'     => 'RPG',
                'stock'        => 9999,
                'image'        => '/images/games/cyberpunk.jpg',
                'rating'       => 8.7,
            ],
            [
                'title'        => 'Counter-Strike 2',
                'description'  => 'The largest technical leap in CS history. Rebuilt on the Source 2 engine, CS2 brings cutting-edge visuals and gameplay.',
                'price'        => 0,
                'release_date' => '2023-09-27',
                'developer'    => 'Valve',
                'publisher'    => 'Valve',
                'category'     => 'Shooter',
                'stock'        => 9999,
                'image'        => '/images/games/cs2.jpg',
                'rating'       => 8.5,
            ],
            [
                'title'        => 'EA SPORTS FC 25',
                'description'  => 'The world\'s most popular football game returns with real-world players, improved AI, and Ultimate Team.',
                'price'        => 569000,
                'release_date' => '2024-09-27',
                'developer'    => 'EA Vancouver',
                'publisher'    => 'EA Sports',
                'category'     => 'Sports',
                'stock'        => 9999,
                'image'        => '/images/games/fc24.jpg',
                'rating'       => 7.9,
            ],
            [
                'title'        => 'Red Dead Redemption 2',
                'description'  => 'Epic tale of outlaw Arthur Morgan in the American frontier. One of the greatest open-world games ever made.',
                'price'        => 429000,
                'release_date' => '2019-11-05',
                'developer'    => 'Rockstar Games',
                'publisher'    => 'Rockstar Games',
                'category'     => 'Action',
                'stock'        => 9999,
                'image'        => '/images/games/rdr2.jpg',
                'rating'       => 9.7,
            ],
            [
                'title'        => 'The Witcher 3: Wild Hunt',
                'description'  => 'A story-driven RPG set in an open world. Play as Geralt of Rivia and hunt a powerful enemy while protecting those you love.',
                'price'        => 299000,
                'release_date' => '2015-05-19',
                'developer'    => 'CD Projekt Red',
                'publisher'    => 'CD Projekt Red',
                'category'     => 'RPG',
                'stock'        => 9999,
                'image'        => '/images/games/witcher3.jpg',
                'rating'       => 9.6,
            ],
            [
                'title'        => 'Sekiro: Shadows Die Twice',
                'description'  => 'Explore the corrupt Sengoku Japan. Master the Shinobi combat system in this action-adventure from FromSoftware.',
                'price'        => 449000,
                'release_date' => '2019-03-22',
                'developer'    => 'FromSoftware',
                'publisher'    => 'FromSoftware',
                'category'     => 'Action',
                'stock'        => 9999,
                'image'        => '/images/games/sekiro.jpg',
                'rating'       => 9.1,
            ],
            [
                'title'        => 'Hades',
                'description'  => 'Defy the god of the dead as you hack and slash through the Underworld in this rogue-like dungeon crawler from Supergiant Games.',
                'price'        => 199000,
                'release_date' => '2020-09-17',
                'developer'    => 'Supergiant Games',
                'publisher'    => 'Supergiant Games',
                'category'     => 'Action',
                'stock'        => 9999,
                'image'        => '/images/games/hades.jpg',
                'rating'       => 9.4,
            ],
            [
                'title'        => 'Grand Theft Auto V',
                'description'  => 'Explore the sprawling city of Los Santos in this action-adventure masterpiece. Now enhanced for PC with GTA Online.',
                'price'        => 299000,
                'release_date' => '2015-04-14',
                'developer'    => 'Rockstar Games',
                'publisher'    => 'Rockstar Games',
                'category'     => 'Action',
                'stock'        => 9999,
                'image'        => '/images/games/gta5.jpg',
                'rating'       => 9.1,
            ],
            [
                'title'        => 'PUBG: BATTLEGROUNDS',
                'description'  => 'The iconic battle royale that started it all. 100 players drop into a shrinking map — only one survives.',
                'price'        => 0,
                'release_date' => '2017-12-21',
                'developer'    => 'PUBG Studios',
                'publisher'    => 'PUBG Corporation',
                'category'     => 'Battle Royale',
                'stock'        => 9999,
                'image'        => '/images/games/pubg.jpg',
                'rating'       => 7.8,
            ],
            [
                'title'        => 'Delta Force: Hawk Ops',
                'description'  => 'A tactical military shooter combining large-scale warfare with intense squad-based gameplay. Free to play.',
                'price'        => 0,
                'release_date' => '2024-10-15',
                'developer'    => 'TiMi Studio',
                'publisher'    => 'TiMi Studio',
                'category'     => 'Shooter',
                'stock'        => 9999,
                'image'        => '/images/games/delta_force.jpg',
                'rating'       => 7.6,
            ],
            [
                'title'        => 'Forza Horizon 5',
                'description'  => 'Race across a breathtaking open world in Mexico. The best racing game experience with 500+ cars.',
                'price'        => 499000,
                'release_date' => '2021-11-09',
                'developer'    => 'Playground Games',
                'publisher'    => 'Playground Games',
                'category'     => 'Racing',
                'stock'        => 9999,
                'image'        => '/images/games/forza.jpg',
                'rating'       => 9.2,
            ],
            [
                'title'        => 'DOTA 2',
                'description'  => 'Valve\'s iconic MOBA. Two teams of five compete to destroy the enemy Ancient. Fully free to play with thousands of hours of depth.',
                'price'        => 0,
                'release_date' => '2013-07-09',
                'developer'    => 'Valve',
                'publisher'    => 'Valve / IceFrog',
                'category'     => 'MOBA',
                'stock'        => 9999,
                'image'        => '/images/games/dota2.jpg',
                'rating'       => 8.8,
            ],
            [
                'title'        => 'League of Legends',
                'description'  => 'The world\'s most played online game. Choose from 165+ champions in 5v5 battles on the iconic Summoner\'s Rift.',
                'price'        => 0,
                'release_date' => '2009-10-27',
                'developer'    => 'Riot Games',
                'publisher'    => 'Riot Games',
                'category'     => 'MOBA',
                'stock'        => 9999,
                'image'        => '/images/games/lol.jpg',
                'rating'       => 8.3,
            ],
            [
                'title'        => 'F1 24',
                'description'  => 'Experience the thrill of Formula 1 in the most authentic F1 game. Race as your favourite drivers on all official tracks.',
                'price'        => 549000,
                'release_date' => '2024-05-31',
                'developer'    => 'Codemasters',
                'publisher'    => 'Codemasters / EA',
                'category'     => 'Racing',
                'stock'        => 9999,
                'image'        => '/images/games/f1_24.jpg',
                'rating'       => 7.5,
            ],
            [
                'title'        => 'Baldur\'s Gate 3',
                'description'  => 'Gather your party and return to the Forgotten Realms in a tale of fellowship, betrayal, sacrifice and survival in this epic RPG.',
                'price'        => 599000,
                'release_date' => '2023-08-03',
                'developer'    => 'Larian Studios',
                'publisher'    => 'CD Projekt Red',
                'category'     => 'RPG',
                'stock'        => 9999,
                'image'        => '/images/games/bg3.jpg',
                'rating'       => 9.8,
            ],
            [
                'title'        => 'Hogwarts Legacy',
                'description'  => 'An immersive, open-world action RPG set in the 1800s wizarding world. Create your legacy at Hogwarts.',
                'price'        => 499000,
                'release_date' => '2023-02-10',
                'developer'    => 'Avalanche Software',
                'publisher'    => '2K Games',
                'category'     => 'RPG',
                'stock'        => 9999,
                'image'        => '/images/games/hogwarts.jpg',
                'rating'       => 8.4,
            ],
            [
                'title'        => 'Call of Duty: Black Ops 6',
                'description'  => 'The next era of Call of Duty features an all-new omni-movement system and globe-trotting Black Ops story.',
                'price'        => 649000,
                'release_date' => '2024-10-25',
                'developer'    => 'Treyarch / Raven',
                'publisher'    => 'Activision',
                'category'     => 'Shooter',
                'stock'        => 9999,
                'image'        => '/images/games/bo6.jpg',
                'rating'       => 8.0,
            ],
            [
                'title'        => 'God of War',
                'description'  => 'Kratos and his son Atreus journey across the Nine Realms of Norse mythology in this action-adventure masterpiece.',
                'price'        => 399000,
                'release_date' => '2022-01-14',
                'developer'    => 'Santa Monica Studio',
                'publisher'    => 'Sony Interactive',
                'category'     => 'Action',
                'stock'        => 9999,
                'image'        => '/images/games/gow.jpg',
                'rating'       => 9.5,
            ],
            [
                'title'        => 'Spider-Man Remastered',
                'description'  => 'Be Spider-Man as he traverses New York City in this open-world action-adventure. Swing through Manhattan and stop villains.',
                'price'        => 449000,
                'release_date' => '2022-08-12',
                'developer'    => 'Insomniac Games',
                'publisher'    => 'Sony Interactive',
                'category'     => 'Action',
                'stock'        => 9999,
                'image'        => '/images/games/spiderman.jpg',
                'rating'       => 9.0,
            ],
            [
                'title'        => 'Minecraft',
                'description'  => 'The best-selling game of all time. Build, survive, and explore infinite procedurally generated worlds.',
                'price'        => 199000,
                'release_date' => '2011-11-18',
                'developer'    => 'Mojang Studios',
                'publisher'    => 'Valve',
                'category'     => 'Sandbox',
                'stock'        => 9999,
                'image'        => '/images/games/minecraft.jpg',
                'rating'       => 9.3,
            ],
            [
                'title'        => 'Resident Evil 4 Remake',
                'description'  => 'A reimagining of the groundbreaking survival horror classic. Leon S. Kennedy fights to rescue the US President\'s daughter.',
                'price'        => 499000,
                'release_date' => '2023-03-24',
                'developer'    => 'Capcom',
                'publisher'    => 'Bandai Namco',
                'category'     => 'Horror',
                'stock'        => 9999,
                'image'        => '/images/games/re4.jpg',
                'rating'       => 9.2,
            ],
            [
                'title'        => 'Overwatch 2',
                'description'  => 'The next evolution of the hero shooter. Free-to-play with 5v5 battles, new heroes, maps, and seasonal events.',
                'price'        => 0,
                'release_date' => '2022-10-04',
                'developer'    => 'Blizzard',
                'publisher'    => 'Blizzard Entertainment',
                'category'     => 'Shooter',
                'stock'        => 9999,
                'image'        => '/images/games/ow2.jpg',
                'rating'       => 7.4,
            ],
            [
                'title'        => 'Assassin\'s Creed Odyssey',
                'description'  => 'Write your own epic odyssey in ancient Greece in this massive open-world RPG inspired by classical history.',
                'price'        => 299000,
                'release_date' => '2018-10-05',
                'developer'    => 'Ubisoft Quebec',
                'publisher'    => 'Ubisoft',
                'category'     => 'RPG',
                'stock'        => 9999,
                'image'        => '/images/games/ac_odyssey.jpg',
                'rating'       => 8.5,
            ],
            [
                'title'        => 'Dark Souls III',
                'description'  => 'The third entry in the legendary Dark Souls series. Face incredible enemies in a deeply interconnected world.',
                'price'        => 349000,
                'release_date' => '2016-04-12',
                'developer'    => 'FromSoftware',
                'publisher'    => 'FromSoftware',
                'category'     => 'RPG',
                'stock'        => 9999,
                'image'        => '/images/games/ds3.jpg',
                'rating'       => 9.3,
            ],
            [
                'title'        => 'VALORANT',
                'description'  => 'A 5v5 character-based tactical shooter by Riot Games. Precise gunplay meets unique agent abilities.',
                'price'        => 0,
                'release_date' => '2020-06-02',
                'developer'    => 'Riot Games',
                'publisher'    => 'Riot Games',
                'category'     => 'Shooter',
                'stock'        => 9999,
                'image'        => '/images/games/valorant.jpg',
                'rating'       => 8.6,
            ],
            [
                'title'        => 'Stardew Valley',
                'description'  => 'Build your dream farm, befriend townsfolk, and explore caves in this beloved indie farming RPG.',
                'price'        => 99000,
                'release_date' => '2016-02-26',
                'developer'    => 'ConcernedApe',
                'publisher'    => '2K Games',
                'category'     => 'Simulation',
                'stock'        => 9999,
                'image'        => '/images/games/stardew.jpg',
                'rating'       => 9.4,
            ],
            [
                'title'        => 'Tekken 8',
                'description'  => 'The legendary fighting game franchise returns with the highest-ever quality graphics and Heat System mechanics.',
                'price'        => 599000,
                'release_date' => '2024-01-26',
                'developer'    => 'Bandai Namco',
                'publisher'    => 'Bandai Namco',
                'category'     => 'Fighting',
                'stock'        => 9999,
                'image'        => '/images/games/tekken8.jpg',
                'rating'       => 8.9,
            ],
            [
                'title'        => 'Helldivers 2',
                'description'  => 'Fight for Super Earth\'s democracy in this co-op third-person shooter. Drop into hostile planets and complete missions.',
                'price'        => 399000,
                'release_date' => '2024-02-08',
                'developer'    => 'Arrowhead Game Studios',
                'publisher'    => 'Sony Interactive',
                'category'     => 'Shooter',
                'stock'        => 9999,
                'image'        => '/images/games/helldivers2.jpg',
                'rating'       => 9.0,
            ],
            [
                'title'        => 'Palworld',
                'description'  => 'A multiplayer, open-world survival crafting game where you can befriend and collect mysterious creatures called "Pals".',
                'price'        => 299000,
                'release_date' => '2024-01-19',
                'developer'    => 'Pocket Pair',
                'publisher'    => '2K Games',
                'category'     => 'Sandbox',
                'stock'        => 9999,
                'image'        => '/images/games/palworld.jpg',
                'rating'       => 8.1,
            ],
            [
                'title'        => 'Diablo IV',
                'description'  => 'Return to the dark, gothic world of Sanctuary and face Lilith, daughter of Mephisto. Action RPG at its darkest.',
                'price'        => 599000,
                'release_date' => '2023-06-06',
                'developer'    => 'Blizzard Entertainment',
                'publisher'    => 'Blizzard Entertainment',
                'category'     => 'RPG',
                'stock'        => 9999,
                'image'        => '/images/games/diablo4.jpg',
                'rating'       => 8.3,
            ],
        ];

        foreach ($games as $data) {
            $publisherId = Publisher::where('name', $data['publisher'])->value('id');
            $categoryId  = Category::where('name', $data['category'])->value('id');

            if (!$publisherId || !$categoryId) continue;

            Game::firstOrCreate(
                ['title' => $data['title']],
                [
                    'description'  => $data['description'],
                    'price'        => $data['price'],
                    'release_date' => $data['release_date'],
                    'developer'    => $data['developer'],
                    'publisher_id' => $publisherId,
                    'category_id'  => $categoryId,
                    'stock'        => $data['stock'],
                    'image'        => $data['image'],
                    'rating'       => $data['rating'],
                ]
            );
        }
    }
}
